apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: new-app
  namespace: new-app
spec:
  destination:
    namespace: new-app
    server: https://kubernetes.default.svc
  source:
    path: 0-Demo_Files/Nginx_Deployment_ArgoCD_Apps
    repoURL: https://github.com/jehadkalifah/ArgoCD-Complete-Master-Course.git
    targetRevision: HEAD
  sources: []
  project: my-project
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
